version directory install.sh cannot work, because it does not have a channel; install.sh gets edited when a version is promoted

diff --git a/darwin/dev-install b/darwin/dev-install
--- a/darwin/dev-install
+++ b/darwin/dev-install
@@ -32,6 +32,8 @@ perl remove-existing-vm.pl
 
 . ./bundler
 
-(curl -s -S -f "$repo/$bundle_name/$bundle_os_machine/$bundle_channel/install.sh" \
-    || echo 'echo curl failed; exit 99') \
-    | bash -e ${debug+-x}
+if [[ ! $no_install ]]; then
+    (curl -s -S -f "$repo/$bundle_name/$bundle_os_machine/$bundle_channel/install.sh" \
+        || echo 'echo curl failed; exit 99') \
+        | bash -e ${debug+-x}
+fi
